### **1) Import Modules**

In [6]:
import numpy as np
import time

In [7]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


### **2) Python Lists**

Python Lists are flexible data types but are not optimized for numerical computation.

In [8]:
# 1d list
x_list_1d = [1, 2, 3, 4]

print(x_list_1d)
print(type(x_list_1d))
print(len(x_list_1d))

[1, 2, 3, 4]
<class 'list'>
4


In [9]:
# 2d list
x_list_2d = [[1,'cat',3], [True,5]]

print(x_list_2d)
print(type(x_list_2d))
print(len(x_list_2d))

[[1, 'cat', 3], [True, 5]]
<class 'list'>
2


### **3) NumPy Arrays from Lists**

The simplest way to create a NumPy is to convert a Python list.

In [10]:
# 1d array
x_1d = np.array([1, 2, 3, 4])

print(x_1d)
print(type(x_1d))
print(x_1d.ndim, x_1d.shape, x_1d.dtype)

[1 2 3 4]
<class 'numpy.ndarray'>
1 (4,) int64


In [11]:
# 2d array
x_2d = np.array(
    [
      [1.5,2,3],
      [4,5,6]
    ]
  )

print(x_2d)
print(type(x_2d))
print(x_2d.ndim, x_2d.shape, x_2d.dtype)

[[1.5 2.  3. ]
 [4.  5.  6. ]]
<class 'numpy.ndarray'>
2 (2, 3) float64


In [12]:
# 3d array
x_3d = np.array(
    [
      [[1,2,3], [4,5,6]],
      [[7,8,9], [10,11,12]]
    ]
)

print(x_3d)
print(type(x_3d))
print(x_3d.ndim, x_3d.shape, x_3d.dtype)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>
3 (2, 2, 3) int64


### **4) Creating NumPy Arrays with Built-in Functions**

NumPy arrays can be created in many different ways using NumPy initialization functions.

In [13]:
# array of zeros
zeros_array = np.zeros(shape=(3, 4, 5))
print(zeros_array)
print(zeros_array.shape)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
(3, 4, 5)


In [14]:
# array of ones
ones_array = np.ones(shape=(2,3))
print(ones_array)
print(ones_array.shape)

[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)


In [15]:
# array of constant values
constant_array = np.full((4,), 10)
print(constant_array)
print(constant_array.shape)

[10 10 10 10]
(4,)


In [16]:
# random array of decimals
random_array = np.random.rand(2,3)
print(random_array)

[[0.78088752 0.90270704 0.235033  ]
 [0.48100561 0.63623465 0.35109316]]


In [17]:
# random array of ints
random_ints_array = np.random.randint(0, 10, size=(3,3))
print(random_ints_array)

[[0 0 9]
 [7 1 1]
 [0 4 1]]


In [18]:
# 1d array of equally spaced decimals
array_equally_spaced_1d = np.linspace(3, 10, 5)
print(array_equally_spaced_1d )

[ 3.    4.75  6.5   8.25 10.  ]


### 5) Indexing, Slicing, and Boolean **Masking**

The elements of NumPy arrays can be accessed in a variety of ways.

In [19]:
# set seed to make reproducible
np.random.seed(42)

# create a random 3d array
random_3d = np.random.rand(2,3,4)
print(random_3d)

[[[0.37454012 0.95071431 0.73199394 0.59865848]
  [0.15601864 0.15599452 0.05808361 0.86617615]
  [0.60111501 0.70807258 0.02058449 0.96990985]]

 [[0.83244264 0.21233911 0.18182497 0.18340451]
  [0.30424224 0.52475643 0.43194502 0.29122914]
  [0.61185289 0.13949386 0.29214465 0.36636184]]]


In [20]:
# accessing one element
one_element = random_3d[1, 0, 2]
print(one_element)

0.18182496720710062


In [21]:
# slicing X[start:stop:step]
sliced_array = random_3d[:, :2 , 0:4:2]
print(sliced_array)

[[[0.37454012 0.73199394]
  [0.15601864 0.05808361]]

 [[0.83244264 0.18182497]
  [0.30424224 0.43194502]]]


In [22]:
# boolean masking
mask = random_3d > .5
print(mask)
print()

masked_array = random_3d[mask]
print(masked_array)

[[[False  True  True  True]
  [False False False  True]
  [ True  True False  True]]

 [[ True False False False]
  [False  True False False]
  [ True False False False]]]

[0.95071431 0.73199394 0.59865848 0.86617615 0.60111501 0.70807258
 0.96990985 0.83244264 0.52475643 0.61185289]


### **6) Vectorized Elementwise Operations**

Mathematical operations can be performed to all elements of a NumPy array without loops.

In [23]:
# define arrays

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [10, 20, 30],
    [40, 50, 0]
])

print(A)
print(B)
print(A.shape)
print(B.shape)

[[1 2 3]
 [4 5 6]]
[[10 20 30]
 [40 50  0]]
(2, 3)
(2, 3)


In [24]:
# elementwise addition
C = A + B
print(C)

[[11 22 33]
 [44 55  6]]


In [25]:
# elementwise multiplication
C = A * B
print(C)

[[ 10  40  90]
 [160 250   0]]


In [26]:
# scalar operations
C = 5 * A
print(C)

[[ 5 10 15]
 [20 25 30]]


In [27]:
# mathematical functions
C = np.sin(B)
print(C)

[[-0.54402111  0.91294525 -0.98803162]
 [ 0.74511316 -0.26237485  0.        ]]


In [28]:
# vectorized operations are much faster than python loops

# create 1d array of ones with 10,000,000 elements
x = np.ones(10_000_000)

# for loop to add 1 to every element
start = time.time()
[element + 1 for element in x]
print('For Loop Time:', round(time.time() - start, 2), 'seconds')

# numpy vectorized
start = time.time()
x + 1
print('NumPy Vectorized Time:', round(time.time() - start,2), 'seconds')

For Loop Time: 1.63 seconds
NumPy Vectorized Time: 0.04 seconds


### **7) Some Useful Functions**

In [29]:
# reshaping arrays

A = np.array([
    [1, 2, 3, 4, 5, 6],
    [7, 8, 9, 10, 11, 12]
])
print(A)
print(A.shape)
print()

B = A.reshape(3,4)
print(B)
print(B.shape)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [30]:
# concatenating arrays

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(A)
print(B)
print(A.shape, B.shape)
print()

# concatenate across rows
C = np.concatenate([A, B], axis=0)
print(C)
print(C.shape)
print()

# concatenate across columns
D = np.concatenate([A, B], axis=1)
print(D)
print(D.shape)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
(2, 2) (2, 2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)

[[1 2 5 6]
 [3 4 7 8]]
(2, 4)


In [31]:
# aggregate functions
A = np.array([
    [1, 2, 3, 4, 5, 6],
    [7, 8, 9, 10, 11, 12]
])
print(A)
print(A.shape)
print()

# sum down rows
print(A.sum(axis=0))
print()

# sum across columns
print(A.sum(axis=1))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)

[ 8 10 12 14 16 18]

[21 57]


In [32]:
# flattening arrays
A = np.array([
    [1, 2, 3, 4, 5, 6],
    [7, 8, 9, 10, 11, 12]
])
print(A)
print(A.shape)
print()

flattened = A.flatten()
print(flattened)
print(flattened.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


### **8) Broadcasting**

Broadcasting allows NumPy to perform operations on arrays of different shapes without copying the data. Arrays are compatible for broadcasting if comparing the dimensions from right to left follows the rules below.

1. Dimensions are equal, or
2. One of the dimensions is 1, or
3. One array doesnt have that dimension


In [33]:
# scalar operations use broadcasting

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(A)
print(A.shape)
print()

B = A + 10
print(B)

[[1 2 3]
 [4 5 6]]
(2, 3)

[[11 12 13]
 [14 15 16]]


In [34]:
# adding a 2d and 1d array

row = np.array([10, 20, 30])
print(row)
print('Row Array Shape', row.shape)
print('A Shape', A.shape)
print()

C = A + row
print(C)

[10 20 30]
Row Array Shape (3,)
A Shape (2, 3)

[[11 22 33]
 [14 25 36]]


In [35]:
# adding a 2d and 1d array in failure case

row = np.array([10, 20])
print(row)
print('Row Array Shape:', row.shape)
print('A Shape', A.shape)
print()

C = A + row
print(C)

[10 20]
Row Array Shape: (2,)
A Shape (2, 3)



ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [ ]:
# adding a 2d and 1d array in failure case fixed with reshaping

col = np.array([10, 20]).reshape(-1,1)
print(col)
print('Col Array Shape:', col.shape)
print('A Shape', A.shape)
print()

C = A + col
print(C)

[[10]
 [20]]
Col Array Shape: (2, 1)
A Shape (2, 3)

[[11 12 13]
 [24 25 26]]


### **9) Vectorized Array Multiplication**

In [ ]:
# dot product
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])
print(x)
print(y)
print(x.shape, y.shape)
print()

z = np.dot(x,y)
print(z)

[1 2 3 4]
[5 6 7 8]
(4,) (4,)

70


In [ ]:
# matrix multiplication

np.random.seed(42)

A = np.random.rand(3,4)
B = np.random.rand(4,5)

print(A)
print(B)
print(A.shape)
print(B.shape)
print()

C = A @ B
print(C)
print(C.shape)

# mismatched dimensions
D = B @ A

[[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]]
[[0.83244264 0.21233911 0.18182497 0.18340451 0.30424224]
 [0.52475643 0.43194502 0.29122914 0.61185289 0.13949386]
 [0.29214465 0.36636184 0.45606998 0.78517596 0.19967378]
 [0.51423444 0.59241457 0.04645041 0.60754485 0.17052412]]
(3, 4)
(4, 5)

[[1.33237553 1.11301448 0.70662485 1.58884557 0.49481545]
 [0.67412212 0.6349249  0.14052267 0.69590694 0.22852944]
 [1.37673411 1.01561875 0.36994977 1.14890965 0.45115957]]
(3, 5)


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 5)

### **10) Helpful Functions for Assignment #1**

In [ ]:
# transpose
A = np.array([
    [1, 2, 3, 4, 5, 6],
    [7, 8, 9, 10, 11, 12]
])
print(A)
print(A.shape)
print()

B = A.T
print(B)
print(B.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)

[[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]
(6, 2)


In [ ]:
# horizontal stack
A = np.array([
    [1, 2, 3, 4, 5, 6],
    [7, 8, 9, 10, 11, 12]
])
print(A)
print(A.shape)
print()

B = np.array([[100], [101]])
print(B)
print(B.shape)
print()

C = np.hstack((A, B))
print(C)
print(C.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)

[[100]
 [101]]
(2, 1)

[[  1   2   3   4   5   6 100]
 [  7   8   9  10  11  12 101]]
(2, 7)


In [ ]:
# matrix inverse
A = np.array([
    [1,2],
    [3,4]
])
print(A)
print(A.shape)
print()

B = np.linalg.inv(A)
print(B)
print(B.shape)

[[1 2]
 [3 4]]
(2, 2)

[[-2.   1. ]
 [ 1.5 -0.5]]
(2, 2)


In [ ]:
# mean
x = np.array([1,2,3,4,5])
print(x)
print(x.shape)
print()

print(np.mean(x))


[1 2 3 4 5]
(5,)

3.0
