### **1) Import Modules**

In [6]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
import numpy as np
import time

### **2) Python Lists**

Python Lists are flexible data types but are not optimized for numerical computation.

In [8]:
# 1d list
x_list_1d = [1, 2, 3, 4]

print(x_list_1d)
print(type(x_list_1d))
print(len(x_list_1d))

[1, 2, 3, 4]
<class 'list'>
4


In [9]:
# 2d list
x_list_2d = [[1,'cat',3], [True,5]]

print(x_list_2d)
print(type(x_list_2d))
print(len(x_list_2d))

[[1, 'cat', 3], [True, 5]]
<class 'list'>
2


### **3) NumPy Arrays from Lists**

The simplest way to create a NumPy is to convert a Python list.

In [ ]:
# 1d array
x_1d = np.array([1, 2, 3, 4])

print(x_1d)
print(type(x_1d))
print(x_1d.ndim, x_1d.shape, x_1d.dtype)

reshape1 = x_1d.reshape(2,2)
print("reshaped: ",reshape1.ndim, reshape1.shape)
print(reshape1)

#shape of (4,1,2) would have ndim = 3
# trick is count variables of the shape to get dimensions

[1 2 3 4]
<class 'numpy.ndarray'>
1 (4,) int64
reshaped:  2 (2, 2)
[[1 2]
 [3 4]]


In [14]:
# 2d array
x_2d = np.array(
    [
      [1.5,2,3],
      [4,5,6]
    ]
  )

print(x_2d) 
print(type(x_2d))
print(x_2d.ndim, x_2d.shape, x_2d.dtype)

[[1.5 2.  3. ]
 [4.  5.  6. ]]
<class 'numpy.ndarray'>
2 (2, 3) float64


In [17]:
# 3d array

#read blocks, rows, numbers 
x_3d = np.array(
    [
      [[1,2,3], [4,5,6]], #block 1
      [[7,8,9], [10,11,12]] #block 2 
    ]
    #contain 2 rows per block 
    # contains 3 numbers per row 
)
# 2 x 2 x 3 = 12 numbers in the 3d array 
print(x_3d)
print(type(x_3d))
print(x_3d.ndim, x_3d.shape, x_3d.dtype)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>
3 (2, 2, 3) int64


### **4) Creating NumPy Arrays with Built-in Functions**

NumPy arrays can be created in many different ways using NumPy initialization functions.

In [18]:
# array of zeros
zeros_array = np.zeros(shape=(3, 4, 5))
print(zeros_array)
print(zeros_array.shape)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
(3, 4, 5)


In [19]:
# array of ones
ones_array = np.ones(shape=(2,3))
print(ones_array)
print(ones_array.shape)

[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)


In [20]:
# array of constant values
constant_array = np.full((4,), 10)
print(constant_array)
print(constant_array.shape)

[10 10 10 10]
(4,)


In [21]:
# random array of decimals
random_array = 10* np.random.rand(2,3)

print(random_array)

[[0.66931933 4.33735931 5.04913488]
 [7.83431555 7.95896002 1.69667297]]


In [30]:
# random array of ints
random_ints_array = np.random.randint(0, 10, size=(3,3))
#print(random_ints_array)

test = np.random.randint(1,8, size=(1,2,2,4))
print(test)

[[[[3 3 1 5]
   [7 1 4 3]]

  [[1 3 1 3]
   [4 3 4 2]]]]


In [ ]:
# 1d array of equally spaced decimals
array_equally_spaced_1d = np.linspace(3, 10, 5)
# 3 is where the array starts, 10 is where it ends, 5 is # of numbers in the array 
print(array_equally_spaced_1d )

[ 3.    4.75  6.5   8.25 10.  ]


### 5) Indexing, Slicing, and Boolean **Masking**

The elements of NumPy arrays can be accessed in a variety of ways.

In [46]:
# set seed to make reproducible
np.random.seed(3)

# create a random 3d array
random_3d = np.random.rand(2,3,4)
print(random_3d)

[[[0.5507979  0.70814782 0.29090474 0.51082761]
  [0.89294695 0.89629309 0.12558531 0.20724288]
  [0.0514672  0.44080984 0.02987621 0.45683322]]

 [[0.64914405 0.27848728 0.6762549  0.59086282]
  [0.02398188 0.55885409 0.25925245 0.4151012 ]
  [0.28352508 0.69313792 0.44045372 0.15686774]]]


In [48]:
# accessing one element
one_element = random_3d[1, 0, 2]
#selects the 2nd block, 1st row and 3rd number. Indices start at 0 
print(one_element)

0.6762549019801313


In [55]:
# slicing X[start:stop:step]
testarr = np.array([
    [[ 1,  2,  3,  4],
     [ 5,  6,  7,  8],
     [ 9, 10, 11, 12]],

    [[13, 14, 15, 16],
     [17, 18, 19, 20],
     [21, 22, 23, 24]]
])
sliced_array = testarr[:, :2 , 0:4:2]
print(sliced_array)

#all blocks " : "
#first two rows " :2 "
#start from 0 to 4 columns but skip by 2 

[[[ 1  3]
  [ 5  7]]

 [[13 15]
  [17 19]]]


In [56]:
# boolean masking
mask = random_3d > .5
print(mask)
print()

masked_array = random_3d[mask]
print(masked_array)

[[[ True  True False  True]
  [ True  True False False]
  [False False False False]]

 [[ True False  True  True]
  [False  True False False]
  [False  True False False]]]

[0.5507979  0.70814782 0.51082761 0.89294695 0.89629309 0.64914405
 0.6762549  0.59086282 0.55885409 0.69313792]


### **6) Vectorized Elementwise Operations**

Mathematical operations can be performed to all elements of a NumPy array without loops.

In [57]:
# define arrays

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [10, 20, 30],
    [40, 50, 0]
])

print(A)
print(B)
print(A.shape)
print(B.shape)

[[1 2 3]
 [4 5 6]]
[[10 20 30]
 [40 50  0]]
(2, 3)
(2, 3)


In [59]:
# elementwise addition
C = A + B
print(C)

[[11 22 33]
 [44 55  6]]


In [60]:
# elementwise multiplication
C = A * B
print(C)

[[ 10  40  90]
 [160 250   0]]


In [61]:
# scalar operations
C = 5 * A
print(C)

[[ 5 10 15]
 [20 25 30]]


In [62]:
# mathematical functions
C = np.sin(B)
print(C)

[[-0.54402111  0.91294525 -0.98803162]
 [ 0.74511316 -0.26237485  0.        ]]


In [ ]:
#compare every pair of dimensions from right to left. 
# Each pair must be EQUAL from the farthest right value, OR one dimension must be 1

In [63]:
# vectorized operations are much faster than python loops

# create 1d array of ones with 10,000,000 elements
x = np.ones(10_000_000)

# for loop to add 1 to every element
start = time.time()
[element + 1 for element in x]
print('For Loop Time:', round(time.time() - start, 2), 'seconds')

# numpy vectorized
start = time.time()
x + 1
print('NumPy Vectorized Time:', round(time.time() - start,2), 'seconds')

For Loop Time: 2.12 seconds
NumPy Vectorized Time: 0.06 seconds


### **7) Some Useful Functions**

In [ ]:
# reshaping arrays

#Reshape rule: The total number of values must stay the same. 
# Multiply the original shape numbers and the new shape numbers; 
# the products must match. Reshape rearranges the values in order—it doesn’t add or remove them
#cant turn 2,3 to 3,4 ; 6 to 12 not possible 
A = np.array([
    [1, 2, 3, 4, 5, 6],
    [7, 8, 9, 10, 11, 12]
])
#print(A)
print("A shape: ", A)
print()

B = A.reshape(3,4)
#print(B)
print("B shape:", B)


A shape:  [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

B shape: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# concatenating arrays

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(A)
print(B)
print(A.shape, B.shape)
print()

# concatenate across rows
C = np.concatenate([A, B], axis=0)
print(C)
print(C.shape)
print()

# concatenate across columns
D = np.concatenate([A, B], axis=1)
print(D)
print(D.shape)

In [ ]:
# aggregate functions
A = np.array([
    [1, 2, 3, 4, 5, 6],
    [7, 8, 9, 10, 11, 12]
])
print(A)
print(A.shape)
print()

# sum down rows
print(A.sum(axis=0))
print()

# sum across columns
print(A.sum(axis=1))

In [ ]:
# flattening arrays
A = np.array([
    [1, 2, 3, 4, 5, 6],
    [7, 8, 9, 10, 11, 12]
])
print(A)
print(A.shape)
print()

flattened = A.flatten()
print(flattened)
print(flattened.shape)

### **8) Broadcasting**

Broadcasting allows NumPy to perform operations on arrays of different shapes without copying the data. Arrays are compatible for broadcasting if comparing the dimensions from right to left follows the rules below.

1. Dimensions are equal, or
2. One of the dimensions is 1, or
3. One array doesnt have that dimension


In [ ]:
# scalar operations use broadcasting

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(A)
print(A.shape)
print()

B = A + 10
print(B)

In [ ]:
# adding a 2d and 1d array

row = np.array([10, 20, 30])
print(row)
print('Row Array Shape', row.shape)
print('A Shape', A.shape)
print()

C = A + row
print(C)

In [ ]:
# adding a 2d and 1d array in failure case

row = np.array([10, 20])
print(row)
print('Row Array Shape:', row.shape)
print('A Shape', A.shape)
print()

C = A + row
print(C)

In [ ]:
# adding a 2d and 1d array in failure case fixed with reshaping

col = np.array([10, 20]).reshape(-1,1)
print(col)
print('Col Array Shape:', col.shape)
print('A Shape', A.shape)
print()

C = A + col
print(C)

### **9) Vectorized Array Multiplication**

In [ ]:
# dot product
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])
print(x)
print(y)
print(x.shape, y.shape)
print()

z = np.dot(x,y)
print(z)

In [ ]:
# matrix multiplication

np.random.seed(42)

A = np.random.rand(3,4)
B = np.random.rand(4,5)

print(A)
print(B)
print(A.shape)
print(B.shape)
print()

C = A @ B
print(C)
print(C.shape)

# mismatched dimensions
D = B @ A

### **10) Helpful Functions for Assignment #1**

In [ ]:
# transpose
A = np.array([
    [1, 2, 3, 4, 5, 6],
    [7, 8, 9, 10, 11, 12]
])
print(A)
print(A.shape)
print()

B = A.T
print(B)
print(B.shape)

In [ ]:
# horizontal stack
A = np.array([
    [1, 2, 3, 4, 5, 6],
    [7, 8, 9, 10, 11, 12]
])
print(A)
print(A.shape)
print()

B = np.array([[100], [101]])
print(B)
print(B.shape)
print()

C = np.hstack((A, B))
print(C)
print(C.shape)

In [ ]:
# matrix inverse
A = np.array([
    [1,2],
    [3,4]
])
print(A)
print(A.shape)
print()

B = np.linalg.inv(A)
print(B)
print(B.shape)

In [ ]:
# mean
x = np.array([1,2,3,4,5])
print(x)
print(x.shape)
print()

print(np.mean(x))
